// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {time} from '../models';
import {bson} from '../models';

export function Create(arg1:internal.PrintRecord):Promise<void>;

export function DefaultCreatedAt():Promise<time.Time>;

export function DefaultId():Promise<bson.ObjectID>;

export function DefaultUpdatedAt():Promise<time.Time>;

export function FindByBatchCode(arg1:string):Promise<Array<internal.PrintRecord>>;
