// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['internal']['PrintRecord']['Create'](arg1);
}

export function CreateMany(arg1) {
  return window['go']['internal']['PrintRecord']['CreateMany'](arg1);
}

export function DefaultCreatedAt() {
  return window['go']['internal']['PrintRecord']['DefaultCreatedAt']();
}

export function DefaultId() {
  return window['go']['internal']['PrintRecord']['DefaultId']();
}

export function DefaultUpdatedAt() {
  return window['go']['internal']['PrintRecord']['DefaultUpdatedAt']();
}

export function FindByBatchCode(arg1) {
  return window['go']['internal']['PrintRecord']['FindByBatchCode'](arg1);
}

export function FindByBatchCodes(arg1) {
  return window['go']['internal']['PrintRecord']['FindByBatchCodes'](arg1);
}
