// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count(arg1) {
  return window['go']['internal']['Template']['Count'](arg1);
}

export function Create(arg1) {
  return window['go']['internal']['Template']['Create'](arg1);
}

export function DefaultCreatedAt() {
  return window['go']['internal']['Template']['DefaultCreatedAt']();
}

export function DefaultId() {
  return window['go']['internal']['Template']['DefaultId']();
}

export function DefaultUpdatedAt() {
  return window['go']['internal']['Template']['DefaultUpdatedAt']();
}

export function Delete(arg1) {
  return window['go']['internal']['Template']['Delete'](arg1);
}

export function FindByName(arg1) {
  return window['go']['internal']['Template']['FindByName'](arg1);
}

export function ListByName(arg1, arg2, arg3) {
  return window['go']['internal']['Template']['ListByName'](arg1, arg2, arg3);
}

export function Update(arg1) {
  return window['go']['internal']['Template']['Update'](arg1);
}
