// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function InsertOne(arg1:internal.Template):Promise<internal.Template>;

export function List(arg1:string,arg2:number,arg3:number):Promise<Array<internal.Template>>;

export function QueryByName(arg1:string):Promise<Array<internal.Template>>;
