// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InsertOne(arg1) {
  return window['go']['internal']['Template']['InsertOne'](arg1);
}

export function List(arg1, arg2, arg3) {
  return window['go']['internal']['Template']['List'](arg1, arg2, arg3);
}

export function QueryByName(arg1) {
  return window['go']['internal']['Template']['QueryByName'](arg1);
}
