// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {time} from '../models';
import {bson} from '../models';

export function Count(arg1:string):Promise<number>;

export function Create(arg1:internal.Template):Promise<void>;

export function DefaultCreatedAt():Promise<time.Time>;

export function DefaultId():Promise<bson.ObjectID>;

export function DefaultUpdatedAt():Promise<time.Time>;

export function Delete(arg1:string):Promise<void>;

export function FindByName(arg1:string):Promise<internal.Template>;

export function ListByName(arg1:string,arg2:number,arg3:number):Promise<internal.ListByNameResp>;

export function Update(arg1:internal.Template):Promise<void>;
