// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileSelector(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileSelector'](arg1, arg2, arg3);
}

export function GetPinters() {
  return window['go']['main']['App']['GetPinters']();
}
